#!/usr/bin/env bash
set -euo pipefail

script_dir=$(cd -- "$(dirname -- "$0")" && pwd)
repo_dir=$(cd -- "$script_dir/.." && pwd)
compiler_output_path="$script_dir/builtin_modules.ty"
interpreter_output_path="$repo_dir/tyrion/src/builtin_modules.ty"
temporary_path=$(mktemp "${TMPDIR:-/tmp}/tyrion-builtin-modules.XXXXXX")
trap 'rm -f "$temporary_path"' EXIT

if [[ $# -gt 1 || ($# -eq 1 && $1 != "--check") ]]; then
  echo "usage: $0 [--check]" >&2
  exit 2
fi

printf '%s\n' \
  '# Tyrion Compiler' \
  '# (c) 2026 Dennis Vink — https://drvink.com/' \
  '# Project: https://github.com/dennisvink/' \
  '# SPDX-License-Identifier: MIT' \
  '#' \
  '# Generated by compiler/update_builtin_modules.sh. Do not edit by hand.' \
  '' >"$temporary_path"

emit_source() {
  local name="$1"
  local source_path="$repo_dir/modules/$name.ty"
  printf '\n\ndef builtin_module_%s_source():\n' "$name" >>"$temporary_path"
  awk '
    BEGIN {
      printf "    return \""
    }
    {
      gsub(/\\/, "\\\\")
      gsub(/"/, "\\\"")
      printf "%s\\n", $0
    }
    END {
      printf "\"\n"
    }
  ' "$source_path" >>"$temporary_path"
}

emit_source core
emit_source http
emit_source tls

printf '%s\n' \
  '' \
  '' \
  'def builtin_module_path(name):' \
  '    if name == "core":' \
  '        return "@tyrion/core"' \
  '    if name == "http":' \
  '        return "@tyrion/http"' \
  '    if name == "tls":' \
  '        return "@tyrion/tls"' \
  '    return ""' \
  '' \
  '' \
  'def builtin_module_source_for_path(path):' \
  '    if path == "@tyrion/core":' \
  '        return builtin_module_core_source()' \
  '    if path == "@tyrion/http":' \
  '        return builtin_module_http_source()' \
  '    if path == "@tyrion/tls":' \
  '        return builtin_module_tls_source()' \
  '    return ""' >>"$temporary_path"

if [[ $# -eq 1 ]]; then
  if ! cmp -s "$temporary_path" "$compiler_output_path" ||
    ! cmp -s "$temporary_path" "$interpreter_output_path"; then
    echo "generated built-in module registry is stale; run $0" >&2
    exit 1
  fi
  exit 0
fi

cp "$temporary_path" "$compiler_output_path"
mv "$temporary_path" "$interpreter_output_path"
trap - EXIT
